/*
 * This source file was generated by the Gradle 'init' task
 */
package tiposReferenciaVsTiposValor.app.src.main.java.org.example;

public class App {
  public static void main(String[] args) {
    int p;

    //System.out.println(p);
  }
}
